redis:
  image: redis:3.2.1-alpine
  volumes:
    - ./:/opt/tdc-nosql-redis

app:
  build: .
  volumes:
    - ./:/opt/tdc-nosql-redis
  ports:
    - 9292:9292
  links:
    - redis
  command: ruby -S bundle exec rackup -s Puma --host 0.0.0.0 --port 9292

